# Import Modul

In [62]:
from sklearn import datasets
from matplotlib import pyplot as plt                                            # Untuk Visualisasi
from sklearn.ensemble import HistGradientBoostingClassifier                     # Untuk mengimport modul Gradien Bossting Classifier
from sklearn import svm                                                         # Untuk mengimport modul Support Vector Machine
from sklearn import tree                                                        # Untuk mengimport modul Decicion Tree
from sklearn.naive_bayes import GaussianNB                                      # Untuk mengimport modul naive bayes
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd
import numpy as np

# Data Gathering

In [3]:
data_iris = datasets.load_iris()

In [4]:
data_iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
data_iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
X_train, X_test, ytrain, ytest = train_test_split(data_iris.data,data_iris.target, test_size=0.3, random_state=1234)

# Model

## SVM

In [7]:

model_svm = svm.SVC(probability=True)
model_svm.fit(X_train, ytrain)


SVC(probability=True)

In [8]:
supportvector = model_svm.support_vectors_
support = model_svm.support_
n_support = model_svm.n_support_

In [9]:
predict_svm = model_svm.predict(X_test)

In [10]:
print('Akurasi : ',sum(predict_svm==ytest)/len(predict_svm)*100,'%')

Akurasi :  97.77777777777777 %


In [11]:
predict_proba_svm =  model_svm.predict_proba(X_test)

In [12]:
predict_svm[1]

1

In [13]:
predict_proba_svm[1]

array([0.009838  , 0.83920275, 0.15095925])

In [14]:
def report(predict,ytest):
  accuracy=accuracy_score(predict, ytest)
  precision=precision_score(predict, ytest, average='weighted')
  recall = recall_score(predict, ytest, average='weighted')
  f1_scorey = f1_score(predict, ytest, average='weighted')
  print(f'Accuracy :{accuracy} \n Precision : {precision} \n Recall : {recall} \n F1 Score : {f1_scorey}')
  # return (accuracy, precision, recall, f1_scorey)


In [15]:
report(predict_svm,ytest)

Accuracy :0.9777777777777777 
 Precision : 0.9790849673202615 
 Recall : 0.9777777777777777 
 F1 Score : 0.9776700336700338


In [16]:
from sklearn.metrics import roc_curve
import numpy as np

In [17]:
# num_classes = len(np.unique(ytrain))
# # Compute ROC curve and ROC area for each class
# fpr = dict()
# tpr = dict()
# roc_auc = dict()

# for i in range(num_classes):
#     fpr[i], tpr[i], _ = roc_curve(ytest[:, i], predict_proba_svm[:, i])
#     roc_auc[i] = auc(fpr[i], tpr[i])

# # Plot ROC curves
# plt.figure(figsize=(10, 8))
# for i in range(num_classes):
#     plt.plot(fpr[i], tpr[i], label=f'Class {i} (AUC = {roc_auc[i]:.2f})')

# plt.plot([0, 1], [0, 1], 'k--', lw=2)
# plt.xlabel('False Positive Rate')
# plt.ylabel('True Positive Rate')
# plt.title('ROC Curve for Multi-class Classification')
# plt.legend(loc='lower right')
# plt.show()

In [18]:
# fpr, tpr, thresholds = roc_curve(ytest, predict_proba_svm)

## Naive Bayes

In [19]:
model_nb = GaussianNB()

In [20]:
model_nb.fit(X_train, ytrain)

GaussianNB()

In [21]:
predict_nb = model_nb.predict(X_test)

In [22]:
print('Akurasi : ',sum(predict_nb==ytest)/len(predict_nb)*100,'%')

Akurasi :  95.55555555555556 %


In [23]:
predict_proba_nb =  model_nb.predict_proba(X_test)

In [24]:
predict_nb[0]

1

In [25]:
predict_proba_nb[0]

array([1.13840145e-121, 9.89084080e-001, 1.09159199e-002])

In [26]:
report(predict_nb,ytest)

Accuracy :0.9555555555555556 
 Precision : 0.9555555555555556 
 Recall : 0.9555555555555556 
 F1 Score : 0.9555555555555556


## Decicion Tree

In [27]:
model_dt = tree.DecisionTreeClassifier()

In [28]:
model_dt.fit(X_train, ytrain)

DecisionTreeClassifier()

In [29]:
predict_dt = model_dt.predict(X_test)

In [30]:
print('Akurasi : ',sum(predict_dt==ytest)/len(predict_dt)*100,'%')

Akurasi :  95.55555555555556 %


In [31]:
predict_proba_dt = model_dt.predict_proba(X_test)

In [32]:
predict_dt[10]

1

In [33]:
predict_proba_dt[10]

array([0., 1., 0.])

In [34]:
report (predict_dt,ytest)

Accuracy :0.9555555555555556 
 Precision : 0.9555555555555556 
 Recall : 0.9555555555555556 
 F1 Score : 0.9555555555555556


## Gradien Boosting

In [35]:
model_gb = HistGradientBoostingClassifier(max_iter=100)

In [36]:
model_gb.fit(X_train,ytrain)

HistGradientBoostingClassifier()

In [37]:
predict_gb = model_gb.predict(X_test)

In [38]:
print('Akurasi : ',sum(predict_gb==ytest)/len(predict_gb)*100,'%')

Akurasi :  95.55555555555556 %


In [39]:
predict_proba_gb = model_gb.predict_proba(X_test)

In [40]:
predict_gb[1]

1

In [41]:
predict_proba_gb[1]

array([9.27375368e-06, 9.98282810e-01, 1.70791607e-03])

In [42]:
report (predict_gb,ytest)

Accuracy :0.9555555555555556 
 Precision : 0.9555555555555556 
 Recall : 0.9555555555555556 
 F1 Score : 0.9555555555555556


## KNN

In [43]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=3)

In [44]:
model_knn.fit(X_train,ytrain)

KNeighborsClassifier(n_neighbors=3)

In [45]:
predict_knn = model_knn.predict(X_test)

In [46]:
print('Akurasi : ',sum(predict_knn==ytest)/len(predict_knn)*100,'%')

Akurasi :  97.77777777777777 %


In [47]:
predict_proba_knn = model_knn.predict_proba(X_test)

In [48]:
predict_knn[1]

1

In [49]:
predict_proba_knn[1]

array([0.        , 0.66666667, 0.33333333])

In [50]:
report(predict_knn,ytest)

Accuracy :0.9777777777777777 
 Precision : 0.9796296296296295 
 Recall : 0.9777777777777777 
 F1 Score : 0.9779434092477569


## Random Forest

In [51]:
from sklearn.ensemble import RandomForestClassifier

In [52]:
model_rf = RandomForestClassifier(max_depth=2)

In [53]:
model_rf.fit(X_train,ytrain)

RandomForestClassifier(max_depth=2)

In [54]:
predict_rf = model_rf.predict(X_test)

In [55]:
print('Akurasi : ',sum(predict_rf==ytest)/len(predict_rf)*100,'%')

Akurasi :  97.77777777777777 %


In [56]:
predict_proba_rf = model_rf.predict_proba(X_test)

In [57]:
predict_rf[1]

1

In [58]:
predict_proba_rf[1]

array([0.01610434, 0.86988709, 0.11400857])

In [59]:
report(predict_rf,ytest)

Accuracy :0.9777777777777777 
 Precision : 0.9790849673202615 
 Recall : 0.9777777777777777 
 F1 Score : 0.9776700336700338


# Recap

In [60]:
report(predict_svm,ytest)
report(predict_nb,ytest)
report(predict_dt,ytest)
report(predict_gb,ytest)
report(predict_knn,ytest)
report(predict_rf,ytest)

Accuracy :0.9777777777777777 
 Precision : 0.9790849673202615 
 Recall : 0.9777777777777777 
 F1 Score : 0.9776700336700338
Accuracy :0.9555555555555556 
 Precision : 0.9555555555555556 
 Recall : 0.9555555555555556 
 F1 Score : 0.9555555555555556
Accuracy :0.9555555555555556 
 Precision : 0.9555555555555556 
 Recall : 0.9555555555555556 
 F1 Score : 0.9555555555555556
Accuracy :0.9555555555555556 
 Precision : 0.9555555555555556 
 Recall : 0.9555555555555556 
 F1 Score : 0.9555555555555556
Accuracy :0.9777777777777777 
 Precision : 0.9796296296296295 
 Recall : 0.9777777777777777 
 F1 Score : 0.9779434092477569
Accuracy :0.9777777777777777 
 Precision : 0.9790849673202615 
 Recall : 0.9777777777777777 
 F1 Score : 0.9776700336700338


In [63]:
model= ['Support Vector Machine', 'Naive Bayes', 'Decicion Tree', 'Gradien Boosting', 'K-Nearest Neighbor','Random Forest']
acc =[0.9777,0.9555,0.9555,0.9555,0.9777,0.9777]
pre = [0.9790,0.9555,0.9555,0.9555,0.9796,0.9790]
rec =[0.9777,0.9555,0.9555,0.9555,0.9777,0.9777]
f1s= [0.9776,0.9555,0.9555,0.9555,0.9779,0.9776]

df_pre= pd.DataFrame({ 'Model' : model,
                      'Accuracy' : acc,
                       'Precision':pre,
                       'Recall' : rec,
                       'F1-Score' : f1s
})

df_pre.to_csv('data_acc.csv',index=False)

In [64]:
df_pre

Model  Accuracy  Precision  Recall  F1-Score
0  Support Vector Machine    0.9777     0.9790  0.9777    0.9776
1             Naive Bayes    0.9555     0.9555  0.9555    0.9555
2           Decicion Tree    0.9555     0.9555  0.9555    0.9555
3        Gradien Boosting    0.9555     0.9555  0.9555    0.9555
4      K-Nearest Neighbor    0.9777     0.9796  0.9777    0.9779
5           Random Forest    0.9777     0.9790  0.9777    0.9776

<center>Hobi Data $©$ 2023 <br>
Contributor : Joko Eliyanto, Indra Cahya Ramdani
</center>

